authors/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from . import views

app_name = 'authors'

author_api_router = SimpleRouter()
author_api_router.register(
    'api', 
    views.AuthorViewSet, 
    basename='author-api'
)

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path(
        'dashboard/budget/new/',
        views.DashboardBudget.as_view(),
        name='dashboard_budget_new'
    ),
    path(
        'dashboard/budget/delete/',
        views.DashboardBudgetDelete.as_view(),
        name='dashboard_budget_delete'
    ),
    path(
        'dashboard/budget/<int:id>/edit/',
        views.DashboardBudget.as_view(),
        name='dashboard_budget_edit'
    ),
    path(
        'profile/<int:id>/',
        views.ProfileView.as_view(),
        name='profile'
    ),
]

urlpatterns += author_api_router.urls

budgets/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from budgets import views

# budgets:budget
app_name = 'budgets'

budget_api_v2_router = SimpleRouter()
budget_api_v2_router.register(
    'budgets/api/v2',
    views.BudgetAPIv2ViewSet,
    basename='budgets-api',
)

urlpatterns = [
    path( #budgets-home
        '', 
        views.BudgetListViewHome.as_view(), 
        name="home"
    ), 
    path( #budgets-search
        'budgets/search/', 
        views.BudgetListViewSearch.as_view(), 
        name="search"
    ),
    path(
        'budgets/tags/<slug:slug>/',
        views.BudgetListViewTag.as_view(),
        name="tag"
    ),
    path( #budgets-category
        'budgets/category/<int:category_id>/', 
        views.BudgetListViewCategory.as_view(), 
        name="category"
    ),
    path( #budgets-budget
        'budgets/<int:pk>/', 
        views.BudgetDetail.as_view(), 
        name="budget"
    ), 
    path( #budgets-api
        'budgets/api/v1/',
        views.BudgetListViewHomeApi.as_view(),
        name="budgets_api_v1",
    ),
    path( #budgets-api-detail
        'budgets/api/v1/<int:pk>/',
        views.BudgetDetailAPI.as_view(),
        name="budgets_api_v1_detail",
    ),
    path( #budgets-theory
        'budgets/theory/',
        views.theory,
        name='theory',
    ),
    
    path(
        'budgets/api/v2/tag/<int:pk>/',
        views.tag_api_detail,
        name='budgets_api_v2_tag',
    ),
    path(
        'budgets/api/token/',
        TokenObtainPairView.as_view(),
        name='token_obtain_pair'
    ),
    path(
        'budgets/api/token/refresh/',
        TokenRefreshView.as_view(),
        name='token_refresh'
    ),
    path(
        'budgets/api/token/verify/',
        TokenVerifyView.as_view(),
        name='token_verify'
    ),
    # Por último
    path('', include(budget_api_v2_router.urls)),
]

project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from budgets.views.admin_dashboard import budget_dashboard

admin.site.index_template = 'admin/index.html'

urlpatterns = [
    path('admin/', budget_dashboard),
    path('admin/', admin.site.urls),
    path('', include('budgets.urls')),
    path('authors/', include('authors.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budgets.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/forms/budget_form.py
from collections import defaultdict

from django import forms
from django.core.exceptions import ValidationError

from authors.validators import AuthorBudgetValidator
from budgets.models import Budget
from utils.django_forms import add_attr


class AuthorBudgetForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)

        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')

    class Meta:
        model = Budget
        fields = [
            'title', 'description', 'equipment_brand', 'equipment_model', \
            'equipment_btus', 'preparation_time', 'preparation_time_unit', \
            'servings', 'servings_unit', 'preparation_steps', 'cover', \
            'scheduled_date',
        ]
        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2'
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Cômodo', 'Cômodo'),
                    ('Salão', 'Salão'),
                    ('Sala', 'Sala'),
                    ('Consultório', 'Consultório'),
                ),
            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Dias', 'Dias'),
                    ('Horas', 'Horas'),
                ),
            ),
            'scheduled_date': forms.DateInput(
                attrs={'type': 'date'}
            ),
        }

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        AuthorBudgetValidator(self.cleaned_data, ErrorClass=ValidationError)

        return super_clean

budgets/views.py
import os

from django.db.models import F, Q
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.http.response import Http404
from django.shortcuts import render
from django.utils import translation
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView

from tag.models import Tag
#from utils.budgets.factory import make_budget
from utils.pagination import make_pagination

from .models import Budget

PER_PAGE = int(os.environ.get('PER_PAGE', 6))

def theory(request, *args, **kwargs):
    budgets = Budget.objects.values('id', 'title')

    context = {
        'budgets': budgets
    }

    return render(
        request,
        'budgets/pages/theory.html',
        context=context
    )


class BudgetListViewBase(ListView):
    model = Budget
    context_object_name = 'budgets'
    ordering = ['-id']
    template_name = 'budgets/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )
        qs = qs.select_related('author', 'category', 'author__profile')
        qs = qs.prefetch_related('tags')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('budgets'),
            PER_PAGE
        )

        html_language = translation.get_language()

        ctx.update(
            {
                'budgets': page_obj, 
                'pagination_range': pagination_range,
                'html_language': html_language,
            }
        )
        return ctx


class BudgetListViewHome(BudgetListViewBase):
    template_name = 'budgets/pages/home.html'


class BudgetListViewHomeApi(BudgetListViewBase):
    template_name = 'budgets/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        budgets = self.get_context_data()['budgets']
        budgets_list = budgets.object_list.values()

        return JsonResponse(
            list(budgets_list),
            safe=False
        )


class BudgetListViewCategory(BudgetListViewBase):
    template_name = 'budgets/pages/category.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')

        ctx.update({
            'title': f'{ctx.get("budgets")[0].category.name} - '
            f'{category_translation} | '
        })

        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            category__id=self.kwargs.get('category_id')
        )

        if not qs:
            raise Http404()

        return qs


class BudgetListViewTag(BudgetListViewBase):
    template_name = 'budgets/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(
            slug=self.kwargs.get('slug', '')
        ).first()

        if not page_title:
            page_title = 'No budgets found'

        page_title = f'{page_title} - Tag |'

        ctx.update({
            'page_title': page_title,
        })

        return ctx


class BudgetListViewSearch(BudgetListViewBase):
    template_name = 'budgets/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '')

        if not search_term:
            raise Http404()

        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term),
            )
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')

        ctx.update({
            'page_title': f'Search for "{search_term}" |',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })

        return ctx


class BudgetDetail(DetailView):
    model = Budget
    context_object_name = 'budget'
    template_name = 'budgets/pages/budget-view.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_published=True)
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({
            'is_detail_page': True
        })

        return ctx
    

class BudgetDetailAPI(BudgetDetail):
    def render_to_response(self, context, **response_kwargs):
        budget = self.get_context_data()['budget']
        budget_dict = model_to_dict(budget)

        budget_dict['created_at'] = str(budget.created_at)
        budget_dict['updated_at'] = str(budget.updated_at)

        if budget_dict.get('cover'):
            budget_dict['cover'] = self.request.build_absolute_uri() + \
                budget_dict['cover'].url[1:]
        else:
            budget_dict['cover'] = ''

        del budget_dict['is_published']
        del budget_dict['preparation_steps_is_html']

        return JsonResponse(
            budget_dict,
            safe=False,
        )

budgets/views/admin_dashboard.py
from django.contrib.admin.sites import site
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Count
from django.db.models.functions import TruncMonth

from budgets.models import Budget


@staff_member_required
def budget_dashboard(request):
    # Orçamentos por mês
    budgets_by_month = (
        Budget.objects
        .annotate(month=TruncMonth('created_at'))
        .values('month')
        .annotate(count=Count('id'))
        .order_by('month')
    )
    labels_month = [b['month'].strftime('%Y-%m') for b in budgets_by_month]
    data_month = [b['count'] for b in budgets_by_month]

    # Por categoria
    budgets_by_category = (
        Budget.objects
        .values('category__name')
        .annotate(count=Count('id'))
    )
    labels_category = [b['category__name'] for b in budgets_by_category]
    data_category = [b['count'] for b in budgets_by_category]

    # Por tipo de serviço
    budgets_by_service = (
        Budget.objects
        .values('service_type')
        .annotate(count=Count('id'))
    )
    labels_service = [b['service_type'] for b in budgets_by_service]
    data_service = [b['count'] for b in budgets_by_service]

    # Por autor (usuário)
    budgets_by_authors = (
        Budget.objects
        .values('author__username')  # <- importante!
        .annotate(count=Count('id'))
    )
    labels_author = [b['author__username'] for b in budgets_by_authors]
    data_author = [b['count'] for b in budgets_by_authors]

    return site.index(request, extra_context={
        'labels_month': labels_month,
        'data_month': data_month,
        'labels_category': labels_category,
        'data_category': data_category,
        'labels_service': labels_service,
        'data_service': data_service,
        'labels_author': labels_author,
        'data_author': data_author,
    })

budgets/views/api.py
from unicodedata import category

from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from tag.models import Tag

from ..models import Budget
from ..permissions import IsOwner
from ..serializers import BudgetSerializer, TagSerializer


class BudgetAPIv2Pagination(PageNumberPagination):
    page_size = 3
    
class BudgetAPIv2ViewSet(ModelViewSet):
    queryset = Budget.objects.get_published()
    serializer_class = BudgetSerializer
    pagination_class = BudgetAPIv2Pagination
    permission_classes = [IsAuthenticatedOrReadOnly, ]
    http_method_names = ['get', 'options', 'head', 'patch', 'post', 'delete']
    
    def get_serializer_class(self):
        return super().get_serializer_class()

    def get_serializer(self, *args, **kwargs):
        return super().get_serializer(*args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset()

        category_id = self.request.query_params.get('category_id', '')

        if category_id != '' and category_id.isnumeric():
            qs = qs.filter(category_id=category_id)

        return qs

    def get_object(self):
        pk = self.kwargs.get('pk', '')

        obj = get_object_or_404(
            self.get_queryset(),
            pk=pk,
        )

        self.check_object_permissions(self.request, obj)

        return obj

    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return [IsOwner(), ]
        return super().get_permissions()

    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data,
            status=status.HTTP_201_CREATED,
            headers=headers
        )
    
    def partial_update(self, request, *args, **kwarg):
        pk = kwarg.get('pk')
        budget = self.get_object()
        serializer = BudgetSerializer(
            instance=budget,
            data=request.data,
            many=False,
            context={'request': request},
            partial=True,
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            serializer.data,
        )


@api_view()
def tag_api_detail(request, pk):
    tag = get_object_or_404(
        Tag.objects.all(),
        pk=pk
    )
    serializer = TagSerializer(
        instance=tag,
        many=False,
        context={'request': request},
    )
    return Response(serializer.data)

budgets/templates/budgets/partials/budget.html
{% load i18n %}

<div class="budget budget-list-item">
    
    {% if budget.cover %}
        <div class="budget-cover">
            <a href="{{ budget.get_absolute_url }}">
                <img src="{{ budget.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}

    <div class="budget-title-container">
        <h2 class="budget-title">
            <a href="{{ budget.get_absolute_url }}">
                {{ budget.title }}
            </a>
        </h2>
    </div>

    <div class="budget-author">
        {% if budget.author is not None %}
            <span class="budget-author-item">
                {% if budget.author.profile %}
                    <a href="{% url 'authors:profile' budget.author.profile.id %}">
                {% endif %}
                <i class="fas fa-user"></i>
                {% if budget.author.first_name %}
                    {{ budget.author.first_name }} {{ budget.author.last_name }}
                {% else %}
                    {{ budget.author.username }}
                {% endif %}
                {% if budget.author.profile %}
                    </a>
                {% endif %}
            </span>
        {% endif %}

        <span class="budget-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ budget.created_at|date:"d/m/Y" }} às {{ budget.created_at|date:"H:i" }}
        </span>

        <span class="budget-author-item">
            <i class="fas fa-tools"></i>
            <span>{{ budget.service_type }}</span>
        </span>

        {% if budget.category is not None %}
            <span class="budget-author-item">
                <a href="{% url 'budgets:category' budget.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ budget.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="budget-content">
        <p>{{ budget.description }}</p>
    </div>


    {% if is_detail_page is not True %}
        <footer class="budget-footer">
            <a class="budget-read-more button button-dark button-full-width" href="{% url 'budgets:budget' budget.id %}">
                <i class="fas fa-eye"></i>
                <span>{% translate 'read more' %}...</span>
            </a>
        </footer>
    {% endif %}


    {% comment %} <!-- ==========  ========== -->
Restrição de visualização da mensagem na home, esta parte deve ser mostrada
se for o autor da solicitação ou o staff 
<!-- ==========  ========== --> {% endcomment %}

{% if is_detail_page is True %}
    {% if user == budget.author or user.is_staff %}
        <div class="budget-meta-container">
            <div class="budget-meta budget-preparation">
                <h3 class="budget-meta-title"><i class="fa-solid fa-temperature-arrow-up"></i> {% translate 'Instalation at:' %}</h3>
                <div class="budget-meta-text">
                    {{ budget.preparation_time }} {{ budget.preparation_time_unit }}
                </div>
            </div>
            <div class="budget-meta budget-servings">
                <h3 class="budget-meta-title"><i class="fa-solid fa-temperature-arrow-down"></i> {% translate 'Instalation local:' %}</h3>
                <div class="budget-meta-text">
                    {{ budget.servings }} {{ budget.servings_unit }}
                </div>
            </div>
            <div class="budget-meta budget-scheduled">
                <h3 class="budget-meta-title"><i class="fas fa-calendar-check"></i> {% translate 'Schedule at:' %}</h3>
                <div class="budget-meta-text">
                    {{ budget.scheduled_date|date:"d/m/Y" }} às {{ budget.scheduled_time }}
                </div>
            </div>
            <div class="budget-meta budget-status">
                <h3 class="budget-meta-title"><i class="fas fa-tasks"></i> {% translate 'Status:' %}</h3>
                <div class="budget-meta-text">
                    {{ budget.status }}
                </div>
            </div>
        </div>

        <div class="preparation-steps">
            {% if budget.preparation_steps_is_html is True %}
                {{ budget.preparation_steps|safe }}
            {% else %}
                {{ budget.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>

        {% if budget.tags.all %}
                <p>
                    Tags:
                    {% for tag in budget.tags.all %}
                        <a href="{% url 'budgets:tag' tag.slug %}">
                            {{ tag.name }}
                        </a>, 
                    {% endfor %}
                </p>
        {% endif %}


            <div class="budget-details">
                <div class="author-details">
                    <h3 class="budget-meta-title">Detalhes do Cliente</h3>
                    <div class="budget-meta-text">
                        <p>Nome: {{ budget.author.first_name }} {{ budget.author.last_name }}</p>
                        <p>Telefone: {{ budget.author.phone }}</p>
                        <p>Email: {{ budget.author.email }}</p>
                    </div>
                </div>

                <div class="address-details">
                    <h3 class="budget-meta-title">Endereço</h3>
                    <div class="budget-meta-text">
                        <p>Rua: {{ budget.address.street }}, {{ budget.address.number }}</p>
                        <p>Bairro: {{ budget.address.neighborhood }}</p>
                        <p>Cidade: {{ budget.address.city }}, {{ budget.address.state }}</p>
                        <p>CEP: {{ budget.address.zipcode }}</p>
                    </div>
                </div>

                <div class="equipment-details">
                    <h3 class="budget-meta-title">Equipamento</h3>
                    <div class="budget-meta-text">
                        <p>Marca: {{ budget.equipment.brand }}</p>
                        <p>Modelo: {{ budget.equipment.model }}</p>
                        <p>BTUs: {{ budget.equipment.btus }}</p>
                    </div>
                </div>
            </div>
    </div>
    {% else %}
        <p>Para acessar os detalhes da mensagem, faça seu <a href="{% url 'authors:login' %}">login</a>.</p>
    {% endif %}
{% endif %}
</div>

budgets/templates/budgets/partials/budget_dashboard.html
{% extends "admin/base_site.html" %}
{% load static %}

{% block content %}
<h1>📊 Dashboard de Orçamentos</h1>
<div class="dashboard-charts">
    <div class="chart-container"><canvas id="lineChart"></canvas></div>
    <div class="chart-container"><canvas id="barCategoryChart"></canvas></div>
    <div class="chart-container"><canvas id="doughnutChart"></canvas></div>
    <div class="chart-container" id="author-chart"><canvas id="barAuthorChart"></canvas></div>
</div>
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <style>
        .dashboard-layout {
            display: flex;
            justify-content: space-between;
            gap: 30px;
            align-items: flex-start;
            flex-wrap: nowrap;
        }
    
        .app-section,
        .dashboard-charts,
        .recent-actions {
            flex: 1;
            min-width: 275px;
        }
    
        .dashboard-charts {
            flex: 2;
            background: #222;
            padding: 20px;
            border-radius: 6px;
            text-align: center;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    
        .charts-row {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 20px;
            margin-top: 20px;
            width: 100%;
        }
    
        .chart-container {
            flex: 1 1 30%;   /* flexível, 3 por linha se couber */
            min-width: 250px;
            max-width: 400px;
            height: 250px;
            background: #333;
            padding: 10px;
            border-radius: 4px;
        }
    
        .recent-actions {
            flex: 1;
            max-width: 350px;
            min-width: 275px;
            margin-left: auto; /* <<< empurra pro canto direito */
        }
    
        /* Dois gráficos por linha */
        .charts-row .chart-container {
            width: 48%;
        }
    
        .chart-container#author-chart {
            height: 300px; /* ou até 400px, se tiver muitos autores */
        }
        
    /* Responsividade: empilha os gráficos em telas menores */
    @media (max-width: 900px) {
        .dashboard-layout {
            flex-direction: column;
            gap: 20px;
        }
        .dashboard-charts {
            min-width: unset;
            width: 100%;
        }
        .charts-row .chart-container {
            width: 100%;
            min-width: unset;
        }
    }
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            new Chart(document.getElementById('lineChart').getContext('2d'), {
                type: 'line',
                data: {
                    labels: {{ labels_month|safe }},
                    datasets: [{
                        label: 'Orçamentos por Mês',
                        data: {{ data_month|safe }},
                        borderColor: 'blue',
                        fill: false
                    }]
                }
            });

            new Chart(document.getElementById('barChart').getContext('2d'), {
                type: 'bar',
                data: {
                    labels: {{ labels_category|safe }},
                    datasets: [{
                        label: 'Por Categoria',
                        data: {{ data_category|safe }},
                        backgroundColor: 'green'
                    }]
                }
            });

            new Chart(document.getElementById('doughnutChart').getContext('2d'), {
                type: 'doughnut',
                data: {
                    labels: {{ labels_service|safe }},
                    datasets: [{
                        label: 'Por Tipo de Serviço',
                        data: {{ data_service|safe }},
                        backgroundColor: ['red', 'orange', 'yellow', 'purple']
                    }]
                }
            });

            new Chart(document.getElementById('barChart').getContext('2d'), {
                type: 'bar',
                data: {
                    labels: {{ labels_author|safe }},
                    datasets: [{
                        label: 'Por Cliente',
                        data: {{ data_author|safe }},
                        backgroundColor: 'purple'
                    }]
                }
            });
        });
    </script>
{% endblock %}

budgets/templates/budgets/partials/change_list.html
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
<div class="object-tools">
    <ul>
        <li><a href="{% url 'admin:budget-dashboard' %}">📊 Ver Dashboard</a></li>
    </ul>
</div>
{{ block.super }}
{% endblock %}

budgets/templates/budgets/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'recipes:search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>